apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: 'CI NodeJS 18 Build'
description: 'CI NodeJS 18 Build'

inputs:
  CONTEXT: 
    description: ''
    required: false
    default: . 
  DOCKER-CONFIG:
    required: true
    description: 'Docker config.json'
  DOCKERFILE: 
    required: false
    default: 'Dockerfile'
    description: ''
  KANIKO-DESTINATION:
    description: ''
    required: true
  KANIKO-BUILD-ARGS:
    description: ''
    required: true
  KANIKO-LABELS: 
    description: ''
    required: true
  pre-build-args:
    description: 'NodeJS build arguments'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - id: ci-nodejs18
      uses: docker://node:18
      shell: sh
      run: | 
        npm version

    - id: nodejs18-package-install
      uses: docker://node:18
      shell: sh
      run: | 
        npm version

    - id: nodejs18-build
      uses: docker://node:18
      shell: sh
      run: | 
        npm version

    - id: nodejs18-test
      uses: docker://node:18
      shell: sh
      run: | 
        npm version

    # - id: checkmarx
    #   uses: cloudbees-io/checkmarx
    #   with:
    #       serverURL: "Checkmarx serverURL"
    #       username: "Checkmarx username"
    #       password: "Checkmarx password"
    #       token: ${{ secrets.CHECKMARX_SECRET }}
    #       language: "LANGUAGE_YOURCODELANGUAGE"

    # - id: sonarqube
    #   uses: cloudbees-io/sonarqube
    #   with:
    #       serverURL: "SonarQube server URL"
    #       username: "SonarQube username"
    #       password: "SonarQube password"
    #       language: "LANGUAGE_YOURCODELANGUAGE"

    - name: Write docker config.json
      uses: docker://alpine:3.18
      env:
        DOCKERCONFIGJSON: ${{ inputs.DOCKER-CONFIG }}
      run: | 
        mkdir -p $HOME/.docker
        echo "$" > $HOME/.docker/config.json
        cat $HOME/.docker/config.json

    - id: kaniko
      uses: cloudbees-io/kaniko
      with:
          dockerfile: ${{ inputs.DOCKERFILE }}
          context: ${{ inputs.CONTEXT }}
          destination: ${{ inputs.KANIKO-DESTINATION }}
          build-args: ${{ inputs.KANIKO-BUILD-ARGS }}
          labels: ${{ inputs.KANIKO-LABELS }}
