apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: 'CI NodeJS 18 Build'
description: 'CI NodeJS 18 Build'

# inputs:
#   context:
#     description: 'NodeJS build context'
#     default: ${{ cloudbees.workspace }}
#   build-args:
#     description: 'NodeJS build arguments'
#     required: false
#     default: ''

runs:
  using: composite
  steps:
    - id: ci-nodejs18
      uses: docker://node:18
      shell: sh
      run: | 
        npm version

    - id: nodejs18-package-install
      uses: docker://node:18
      shell: sh
      run: | 
        npm version

    - id: nodejs18-build
      uses: docker://node:18
      shell: sh
      run: | 
        npm version

    - id: nodejs18-test
      uses: docker://node:18
      shell: sh
      run: | 
        npm version

    - id: checkmarx
      uses: cloudbees-io/checkmarx
      with:
          serverURL: "Checkmarx serverURL"
          username: "Checkmarx username"
          password: "Checkmarx password"
          token: ${{ secrets.CHECKMARX_SECRET }}
          language: "LANGUAGE_YOURCODELANGUAGE"

    - id: sonarqube
      uses: cloudbees-io/sonarqube
      with:
          serverURL: "SonarQube server URL"
          username: "SonarQube username"
          password: "SonarQube password"
          language: "LANGUAGE_YOURCODELANGUAGE"

    - id: kaniko
      uses: cloudbees-io/kaniko
      with:
          dockerfile: path/to/Dockerfile
          context: .
          destination: <registry host>/<image name>:1.0.1,<registry host>/<image name>:latest
          build-args: BUILDKIT_CONTEXT_KEEP_GIT_DIR=1,BUILDKIT_INLINE_CACHE=1
          labels: maintainer=John Smith,version=1.0.1
